### ISSUE TITLE
Incompatible with newer Gradle versions

### ISSUE THREAD

**Issue by lostiniceland** [kontext-e/jqa-gradle#1]
I am trying to run the plugin with Gradle 7.1.1 (due to Java 16 as preparation for the next LTS 17) and the plugin seems to use deprecated Gradle API.

https://github.com/lostiniceland/mtmd/tree/jqa
Running `./gradlew :backend-quarkus:scan` produces the following output

```
Caused by: java.lang.NoSuchMethodError: 'org.gradle.process.internal.worker.SingleRequestWorkerProcessBuilder org.gradle.process.internal.worker.WorkerProcessFactory.singleRequestWorker(java.lang.Class, java.lang.Class)'
        at de.kontext_e.jqassistant.gradle.JqassistantWorkerManager.createWorkerProcess(JqassistantWorkerManager.java:25)
        at de.kontext_e.jqassistant.gradle.JqassistantWorkerManager.runWorker(JqassistantWorkerManager.java:16)
        at de.kontext_e.jqassistant.gradle.Jqassistant.process(Jqassistant.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:506)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:491)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:474)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$300(ExecuteActionsTaskExecuter.java:106)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:271)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:249)
        at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:83)
        at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:37)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:50)
        at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:47)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:37)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
        at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:50)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:36)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:29)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:54)
        at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:35)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:60)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:27)
        at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:174)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:74)
        at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:45)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:40)
        at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:29)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:99)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:92)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:52)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:36)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:85)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:42)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:91)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:49)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:106)
        at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:51)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:72)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:46)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:86)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:86)
        at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:32)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:43)
        at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:31)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:40)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$2.withWorkspace(ExecuteActionsTaskExecuter.java:284)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:40)
        at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
        at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
        at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:33)
        at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:185)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:174)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
```

Please note, I am using the Kotlin-DSL for Gradle.

**Comment by dhamann** [comment]
hi there, i was triggered by the fine article about the ddd-stuff that found its way into jqa and also wanted to use the gradle setup.

i think i just read your error message as something that got fixed in https://github.com/kontext-e/jqassistant-gradle-plugin/pull/7 ... but i also think that the persons needed to merge that PR ( @kontext-e ) haven't had found the time to review the PR yet.

maybe that could change if @kontext-e gets nudged a bit? 👋

**Comment by lostiniceland** [comment]
Thanks for the hint. The PR indeed fixes what I also tried in my local setup. 
Furthermore it also splits the plugin usage into another project which helps with the chicken-egg problem.

**Comment by kontext-e** [comment]
Just merged the request and release version 1.0.1. Tried with Gradle 6.8.3 and 7.1.1, worked for me. Please let me know if you still encounter problems.

**Comment by lostiniceland** [comment]
Where is it published? I cannot pull the latest release 

```
   > Could not find de.kontext_e.jqassistant.gradle:jqassistant-gradle-plugin:1.0.1.
     Searched in the following locations:
       - file:/home/marc/.m2/repository/de/kontext_e/jqassistant/gradle/jqassistant-gradle-plugin/1.0.1/jqassistant-gradle-plugin-1.0.1.pom
       - https://repo.maven.apache.org/maven2/de/kontext_e/jqassistant/gradle/jqassistant-gradle-plugin/1.0.1/jqassistant-gradle-plugin-1.0.1.pom

```

**Comment by kontext-e** [comment]
See https://plugins.gradle.org/plugin/de.kontext_e.jqassistant.gradle

**Comment by lostiniceland** [comment]
I double checked there. There seems to be an error during the publish

I tracked it down in the gradle-plugin-repo
https://plugins.gradle.org/m2/de/kontext_e/jqassistant/gradle/de.kontext_e.jqassistant.gradle.gradle.plugin/1.0.1/

See the duplicate gradle.gradle in the artifact name
There is also no 1.0.0. Could it be the case the mistake happened when moving away from jcenter?

**Comment by kontext-e** [comment]
Indeed there is only a 1.0.0-SNAPSHOT. It also has the artifact id de.kontext_e.jqassistant.gradle.gradle.plugin. Apparently this worked for a number of people. 
I guess the double gradle.gradle is some internal stuff from the Gradle publisher, also the groupId gradle.plugin.de.kontext_e.jqassistant.gradle is not what is specified in the plugins build.gradle.
I tried a sample project on a fresh computer. It worked well. That's why I assume the published plugin should work although some entries look suspicious.

**Comment by dhamann** [comment]
after reading your conversation i must admit: i did not understand the consequences of your findings.

if i may bluntly ask ... does it work now? 😊 //edit: iguessiwilljustcheckitoutandtry. whydoievenask 🤕

**Comment by kontext-e** [comment]
@dhamann Did it work? @lostiniceland and me got different results...

**Comment by lostiniceland** [comment]
I found the culprit.

I've accidentally mixed jqa-plugin versions with the git-plugin version from kontext-e
```
plugins("com.buschmais.jqassistant.plugin:junit:${jqaVersion}")
plugins("com.buschmais.jqassistant.plugin:jpa2:${jqaVersion}")
plugins("de.kontext-e.jqassistant.plugin:jqassistant.plugin.git:1.8.0")
```
Instead of 1.8.0 I've had "jqaVersion" which resolved to 1.10.0 for which the Git plugin does not exist. Anyway, the error message was kind of misleading.

**Comment by dhamann** [comment]
> @dhamann Did it work? @lostiniceland and me got different results...

i have tried with 7.1.1, had strange results. wanted to confirm by supplying a simple testbed as my own repo (which fails) ... will do that probably sometimes this week

but then yesterevening i found out about [the examples subproject here](https://github.com/kontext-e/jqassistant-gradle-plugin/tree/master/example) ... which does work a bit different ... but which works somehow ... that confused me some more.

need to play around and will gladly report afterwards @kontext-e 👍

**Comment by dhamann** [comment]
i failed, then got it to work, then failed again ... so let me pre-pose my solution: changing the dependency under plugins to drop `-SNAPSHOT`

### failed: 
using the [Usage-Suggestions](https://github.com/kontext-e/jqassistant-gradle-plugin/blame/master/README.adoc#L17) like adding id "de.kontext_e.jqassistant.gradle" version "1.0.1-SNAPSHOT" to plugins

## succeeded:
 adding `id "de.kontext_e.jqassistant.gradle" version "1.0.1"` to plugins (note the missing `-SNAPSHOT`)

### failed: 
using the [Usage-Suggestions](https://github.com/kontext-e/jqassistant-gradle-plugin/blame/master/README.adoc#L27) by adding the `classpath 'de.kontext_e.jqassistant.gradle:jqassistant-gradle-plugin:1.0.1-SNAPSHOT'` to buildscript/dependencies (failed with or without `-SNAPSHOT`)

### failure message along the line of:
```
* What went wrong:
Plugin [id: 'de.kontext_e.jqassistant.gradle', version: '1.0.1-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'de.kontext_e.jqassistant.gradle:de.kontext_e.jqassistant.gradle.gradle.plugin:1.0.1-SNAPSHOT')
  Searched in the following repositories:
    Gradle Central Plugin Repository
```

So ... 
- i was able to run a scan when i dropped the -SNAPSHOT from adding the line to plugins {} (which might lead to a change in the Line https://github.com/kontext-e/jqassistant-gradle-plugin/blame/master/README.adoc#L17 )
- i failed to follow the Usage-Tips for adding it to the "old buildscript way" with or without -SNAPSHOT (which might lead to changes in the Lines around https://github.com/kontext-e/jqassistant-gradle-plugin/blame/master/README.adoc#L27)
- the Errormessage makes me assume that maybe the gav coordinates are a bit borked (maybe around here: could not resolve plugin artifact 'de.kontext_e.jqassistant.gradle:`de.kontext_e.jqassistant.gradle`.gradle.plugin:1.0.1-SNAPSHOT' ?)

I have not much experience around working with mvn snapshots and the way they are resolved vs "notsnapshots" ... is it important for this plugin to rely on a snapshot? what are the advantages vs "notsnapshots"?

(actually i just stumbled upon this lack of knowledge on my side when inspecting redhat quarkus way of doing things with snapshots where they somewhere always expect a nonexisting version like 9999 ... which must have something to do with the way maven gav coordinates are resolved. but i need to brush up my knowledge there)
